### ISSUE TITLE
Completing the grammar..

### ISSUE THREAD

**Issue by amaanq** [mstanciu552/tree-sitter-matlab#8]
I plan to add this to nvim-treesitter shortly, but I will likely rewrite the grammar soon to complete it and make it look nicer. Please let me know if that's ok with you and if you're still active :)

**Comment by rkmiec** [comment]
I'm not sure if this is a parser that is now used in the current nvim implementation, but it indeed has some issues.
Some of them are related to comments. Keywords in comments are still considered valid jump locations.
Pressing `%` on the last `end` causes nvim to jump between connected words: `for`, `case` and last `end`. The last end should be marked as a parser error as there is no working counterpart for this.
```matlab
% for some reason we should also handle second case
if 2 > 1
  disp('ok');
else
  disp('not ok');
end
end
```

**Comment by mstanciu552** [comment]
I'm not currently active in maintaining this projects as I do not have much free time. But I am on board with anyone who wants to use or improve this.
Thank you very much.
